services:
    backend:
        image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
        restart: always
        networks:
            - default
        env_file:
            - .env

        build:
            context: ./backend
            args:
                INSTALL_DEV: ${INSTALL_DEV-false}

volumes:
  app-db-data:
